[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"
rand = "0.8.5"
getrandom = { version = "0.2.7", features = ["js"] }